import localFont from "next/font/local";
import "./globals.css";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const Grotesk = localFont({
  src : [{
    path : "../public/fonts/FoundersGrotesk-SemiBold.ttf",
  }],
  variable : "--font-grotesk"
});

const Montreal = localFont({
  src : [{
    path : "../public/fonts/NeueMontreal-Regular.ttf"
  }],
  variable : "--font-montreal"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${Montreal.variable} ${geistSans.variable} ${geistMono.variable} ${Grotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
